{
  "openapi": "3.0.1",
  "info": {
    "version": "1.0.0",
    "title": "Kapusta",
    "description": "Documentation for using the Kapusta application",
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/licenses/MIT"
    }
  },
  "consumes": ["application/json"],
  "produces": ["application/json"],
  "servers": [{ "url": "http://localhost:5000" }, {}],
  "tags": [
    {
      "name": "Auth",
      "description": "Authorization endpoints"
    },
    {
      "name": "Users",
      "description": "Users endpoints"
    },
    {
      "name": "Transactions",
      "description": "Transactions endpoints"
    }
  ],
  "paths": {
    "/auth/google": {
      "get": {
        "tags": ["Auth"],
        "summary": "User registration by google service",
        "parameters": [],
        "security": [],
        "requestBody": {
          "description": "Registration's object",
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegistrationRequest"
              }
            }
          }
        },
        "responses": {
          "302": {
            "description": "Found",
            "content": {}
          },
          "304": {
            "description": "Not Modified",
            "content": {}
          },
          "400": {
            "description": "Bad request",
            "content": {}
          }
        }
      }
    },
    "/auth/google-redirect": {
      "get": {
        "tags": ["Auth"],
        "summary": "User registration by google",
        "parameters": [],
        "security": [],
        "requestBody": {
          "description": "Sign by google",
          "required": false,
          "content": {}
        },
        "responses": {
          "302": {
            "description": "Found",
            "content": {}
          },
          "400": {
            "description": "Bad request",
            "content": {}
          }
        }
      }
    },
    "/auth/registration": {
      "post": {
        "tags": ["Auth"],
        "summary": "User registration",
        "parameters": [],
        "security": [],
        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegistrationRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegistrationResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "409": {
            "description": "Such email is registered already",
            "content": {}
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "tags": ["Auth"],
        "summary": "User login",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {}
          },
          "401": {
            "description": "Invalid credential",
            "content": {}
          }
        }
      }
    },
    "/auth/logout": {
      "post": {
        "tags": ["Auth"],
        "summary": "User logout",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Logout user",
          "required": true,
          "content": {}
        },
        "responses": {
          "204": {
            "description": "success",
            "content": {}
          }
        }
      }
    },
    "/users": {
      "get": {
        "tags": ["Users"],
        "summary": "Users info only for ADMIN",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Getting all users",
          "required": false,
          "content": {}
        },
        "responses": {
          "200": {
            "description": "success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetUsersResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {}
          }
        }
      }
    },
    "/users/:id": {
      "get": {
        "tags": ["Users"],
        "summary": "Users info",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "type": "string",
            "description": "User's id"
          }
        ],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Get user info",
          "required": false,
          "content": {}
        },
        "responses": {
          "200": {
            "description": "success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserInfoResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {}
          }
        }
      },
      "delete": {
        "tags": ["Users"],
        "summary": "Delete Users only for ADMIN",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "type": "string",
            "description": "User's id"
          }
        ],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Delete user",
          "required": false,
          "content": {}
        },
        "responses": {
          "200": {
            "description": "success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DeleteUserResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {}
          }
        }
      }
    },
    "/users/:id/update": {
      "put": {
        "tags": ["Users"],
        "summary": "Users info only for ADMIN",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "type": "string",
            "description": "User's id"
          }
        ],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Update users info",
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegistrationRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegistrationResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "403": {
            "description": "Access is denied",
            "content": {}
          }
        }
      }
    },
    "/users/balance": {
      "put": {
        "tags": ["Users"],
        "summary": "Change balance for current user",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Update user`s balance",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateBalanceRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "success",
            "content": {}
          },
          "404": {
            "description": "Not Found",
            "content": {}
          }
        }
      }
    },
    "/transactions": {
      "get": {
        "tags": ["Transactions"],
        "summary": "Get transactions",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "transactions's object",
          "required": false,
          "content": {}
        },
        "responses": {
          "200": {
            "description": "success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TransactionsResponse"
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": ["Transactions"],
        "summary": "Make transaction",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Create transaction object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateNewTransactionRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CreateNewTransactionResponse"
                }
              }
            }
          }
        }
      }
    },
    "/transactions/:id": {
      "delete": {
        "tags": ["Transactions"],
        "summary": "Delete Transactions",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "type": "string",
            "description": "Transaction`s id"
          }
        ],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Delete Transactions object",
          "required": false,
          "content": {}
        },
        "responses": {
          "200": {
            "description": "success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DeleteTransactionResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {}
          }
        }
      }
    },
    "/transactions/month": {
      "get": {
        "tags": ["Transactions"],
        "summary": "Get transactions",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "transactions's object",
          "required": false,
          "content": {}
        },
        "responses": {
          "200": {
            "description": "success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TransactionsResponse"
                }
              }
            }
          }
        }
      }
    },
    "/transactions/summary": {
      "get": {
        "tags": ["Transactions"],
        "summary": "Get transactions",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "transactions's object",
          "required": false,
          "content": {}
        },
        "responses": {
          "200": {
            "description": "success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TransactionsResponse"
                }
              }
            }
          }
        }
      }
    },
    "/transactions/stats": {
      "get": {
        "tags": ["Transactions"],
        "summary": "Get transactions",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "transactions's object",
          "required": false,
          "content": {}
        },
        "responses": {
          "200": {
            "description": "success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TransactionsResponse"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "RegistrationRequest": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          }
        }
      },
      "RegistrationResponse": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "id": {
            "type": "string",
            "description": "User's id",
            "example": "62025fac12117b1ff96783a2"
          },
          "role": {
            "type": "string",
            "description": "User's role in app",
            "example": "user"
          },
          "balance": {
            "type": "number",
            "description": "User's balance",
            "example": 2022
          }
        },
        "example": {
          "id": "62025fac12117b1ff96783a2",
          "name": "Guest",
          "email": "ihor.yatsyshynn@gmail.com",
          "role": "user",
          "balance": 0
        }
      },
      "LoginRequest": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          }
        }
      },
      "LoginResponse": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "User's id",
            "example": "62025fac12117b1ff96783a2"
          },
          "token": {
            "type": "string",
            "description": "User's token for app",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMDI1ZmFjMTIxMTdiMWZmOTY3ODNhMiIsImlhdCI6MTY0NDMyMzc5MSwiZXhwIjoxNjQ0MzY2OTkxfQ.23Y08DlB-pO8B0WLfQ2pfDe3obl5tOAZ7AyWXpHXKRY"
          }
        },
        "example": {
          "id": "62025fac12117b1ff96783a2",
          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMDI1ZmFjMTIxMTdiMWZmOTY3ODNhMiIsImlhdCI6MTY0NDMyMzc5MSwiZXhwIjoxNjQ0MzY2OTkxfQ.23Y08DlB-pO8B0WLfQ2pfDe3obl5tOAZ7AyWXpHXKRY"
        }
      },
      "GetUsersResponse": {
        "type": "object",
        "properties": {
          "total": {
            "type": "integer",
            "description": "Count users",
            "example": 10
          },
          "users": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "balance": {
                  "type": "number",
                  "description": "Current balance user`s",
                  "example": 5000
                },
                "_id": {
                  "type": "string",
                  "description": "Unique id user`s",
                  "example": "62025fac12117b1ff96783a2"
                },
                "name": {
                  "type": "string",
                  "description": "User`s name",
                  "example": "Rostik"
                },
                "email": {
                  "type": "string",
                  "description": "User`s email",
                  "example": "admin@admin.com",
                  "format": "email"
                },
                "password": {
                  "type": "string",
                  "description": "User`s password",
                  "example": "qwert12345"
                },
                "role": {
                  "type": "string",
                  "description": "User`s role for app",
                  "example": "user"
                },
                "token": {
                  "type": "string",
                  "description": "User's token for app",
                  "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMDI1ZmFjMTIxMTdiMWZmOTY3ODNhMiIsImlhdCI6MTY0NDMyMzc5MSwiZXhwIjoxNjQ0MzY2OTkxfQ.23Y08DlB-pO8B0WLfQ2pfDe3obl5tOAZ7AyWXpHXKRY"
                },
                "createdAt": {
                  "type": "string",
                  "description": "User`s data created",
                  "example": "2022-02-04T06:27:31.669Z"
                },
                "updateAt": {
                  "type": "string",
                  "description": "User`s data updated",
                  "example": "2022-02-04T06:27:31.669Z"
                }
              }
            },
            "description": "User's token for app",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMDI1ZmFjMTIxMTdiMWZmOTY3ODNhMiIsImlhdCI6MTY0NDMyMzc5MSwiZXhwIjoxNjQ0MzY2OTkxfQ.23Y08DlB-pO8B0WLfQ2pfDe3obl5tOAZ7AyWXpHXKRY"
          }
        },
        "description": "Count users in cloud",
        "example": {
          "total": 13,
          "users": [
            {
              "balance": 0,
              "_id": "61fcc7533ee7596562f46e97",
              "name": "ADMIN",
              "email": "admin@admin.com",
              "password": "$2a$06$Y6SAbFDlWScj7yaxi.eeyuog4JeluFzyzlNkEOSOL1J9FNjwkQdja",
              "subscription": "starter",
              "role": "administrator",
              "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZmNjNzUzM2VlNzU5NjU2MmY0NmU5NyIsImlhdCI6MTY0NDAyNjQzMCwiZXhwIjoxNjQ0MDY5NjMwfQ.r3QwsK54uNKqonayNSQcQnLBbRISbMB8Th20GJFao2s",
              "createdAt": "2022-02-04T06:27:31.669Z",
              "updatedAt": "2022-02-05T02:00:30.533Z"
            },
            {
              "balance": 0,
              "_id": "61fd1ab1b5a7668232d1b617",
              "name": "ADMIN-rost",
              "email": "rost@admin.com",
              "password": "$2a$06$NwtTmGsT05tM8C.D629PGehGKMyZQib5bzJrnSna1.6lz0jMxCf.y",
              "subscription": "starter",
              "role": "administrator",
              "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZmQxYWIxYjVhNzY2ODIzMmQxYjYxNyIsImlhdCI6MTY0Mzk3NzQzOSwiZXhwIjoxNjQ0MDIwNjM5fQ.TwBKSvF8qAtuY5ipPBwlTIvKZ2sB8WJzmlx0OgIEaNM",
              "createdAt": "2022-02-04T12:23:13.442Z",
              "updatedAt": "2022-02-04T12:23:59.177Z"
            }
          ]
        }
      },
      "UserInfoResponse": {
        "type": "object",
        "properties": {
          "result": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "description": "User's name",
                "example": "Rostik"
              },
              "email": {
                "type": "string",
                "description": "User's email",
                "example": "user1@ordy.com",
                "format": "email"
              },
              "role": {
                "type": "string",
                "description": "User's role",
                "example": "user"
              },
              "balance": {
                "type": "number",
                "description": "User's balance",
                "example": 5000
              }
            },
            "example": {
              "name": "user#1",
              "email": "user1@ordy.com",
              "role": "user",
              "balance": 5000
            }
          }
        }
      },
      "DeleteUserResponse": {
        "type": "object",
        "properties": {
          "deletedUser": {
            "type": "object",
            "properties": {
              "balance": {
                "type": "number",
                "description": "Current balance user`s",
                "example": 5000
              },
              "_id": {
                "type": "string",
                "description": "Unique id user`s",
                "example": "62025fac12117b1ff96783a2"
              },
              "name": {
                "type": "string",
                "description": "User`s name",
                "example": "Rostik"
              },
              "email": {
                "type": "string",
                "description": "User`s email",
                "example": "admin@admin.com",
                "format": "email"
              },
              "password": {
                "type": "string",
                "description": "User`s password",
                "example": "qwert12345"
              },
              "role": {
                "type": "string",
                "description": "User`s role for app",
                "example": "user"
              },
              "token": {
                "type": "string",
                "description": "User's token for app",
                "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMDI1ZmFjMTIxMTdiMWZmOTY3ODNhMiIsImlhdCI6MTY0NDMyMzc5MSwiZXhwIjoxNjQ0MzY2OTkxfQ.23Y08DlB-pO8B0WLfQ2pfDe3obl5tOAZ7AyWXpHXKRY"
              },
              "createdAt": {
                "type": "string",
                "description": "User`s data created",
                "example": "2022-02-04T06:27:31.669Z"
              },
              "updateAt": {
                "type": "string",
                "description": "User`s data updated",
                "example": "2022-02-04T06:27:31.669Z"
              }
            }
          }
        },
        "example": {
          "deletedUser": {
            "balance": 0,
            "_id": "61fd28b1e0566d64abc6f87a",
            "name": "ordinary№2",
            "email": "ordynary2@ordy.com",
            "password": "$2a$06$OMr9dpN5iOWhaCl2D0x5Qu6xVbPj2qG1.eB6aZuDBJvfsloL.bbg2",
            "role": "user",
            "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZmQyOGIxZTA1NjZkNjRhYmM2Zjg3YSIsImlhdCI6MTY0Mzk4MTIyNywiZXhwIjoxNjQ0MDI0NDI3fQ.r0UX3dDxAtEFmJVK24jBhLjdmVj_WnewgDvhSXrntoE",
            "createdAt": "2022-02-04T13:22:57.968Z",
            "updatedAt": "2022-02-04T13:27:07.976Z"
          }
        }
      },
      "UpdateBalanceRequest": {
        "type": "object",
        "required": ["id", "balance"],
        "properties": {
          "id": {
            "type": "string",
            "description": "User's id",
            "example": "6203e5d64ead3ad7e96a1283"
          },
          "balance": {
            "type": "number",
            "description": "User's balance",
            "example": "5000"
          }
        }
      },
      "TransactionsResponse": {
        "type": "object",
        "properties": {
          "total": {
            "type": "integer",
            "description": "Count user`s transactions",
            "example": "25"
          },
          "page": {
            "type": "integer",
            "description": "Count user`s page",
            "example": "2"
          },
          "income": {
            "type": "array",
            "properties": {
              "items": {
                "type": "object",
                "properties": {
                  "day": {
                    "type": "integer",
                    "description": "Day",
                    "example": "10"
                  },
                  "month": {
                    "type": "integer",
                    "description": "Month",
                    "example": "1"
                  },
                  "year": {
                    "type": "integer",
                    "description": "Year",
                    "example": "2022"
                  },
                  "sum": {
                    "type": "number",
                    "description": "Sum",
                    "example": "15000"
                  },
                  "income": {
                    "type": "boolean",
                    "example": true
                  },
                  "category": {
                    "type": "string",
                    "description": "Category",
                    "example": "salary"
                  },
                  "description": {
                    "type": "string",
                    "description": "Description",
                    "example": "зарплата"
                  },
                  "owner": {
                    "type": "object",
                    "properties": {
                      "_id": {
                        "type": "string",
                        "description": "User's id",
                        "example": "62021d2c34b879a2b5970f37"
                      },
                      "name": {
                        "type": "string",
                        "description": "User's name",
                        "example": "Rostik"
                      },
                      "email": {
                        "type": "string",
                        "description": "User's email",
                        "example": "user1@ordy.com",
                        "format": "email"
                      },
                      "role": {
                        "type": "string",
                        "description": "User's role",
                        "example": "user"
                      }
                    }
                  },
                  "createdAt": {
                    "type": "string",
                    "description": "User`s data created",
                    "example": "2022-02-04T06:27:31.669Z"
                  },
                  "updateAt": {
                    "type": "string",
                    "description": "User`s data updated",
                    "example": "2022-02-04T06:27:31.669Z"
                  },
                  "id": {
                    "type": "string",
                    "description": "User's id",
                    "example": "62025fac12117b1ff96783a2"
                  }
                }
              }
            },
            "example": [
              {
                "day": 10,
                "month": 1,
                "year": 2021,
                "sum": 15000,
                "income": true,
                "category": "salary",
                "description": "зарплата",
                "owner": {
                  "_id": "62021d2c34b879a2b5970f37",
                  "name": "TEST",
                  "email": "test@mail.com",
                  "role": "user"
                },
                "createdAt": "2022-02-08T07:39:12.227Z",
                "updatedAt": "2022-02-08T07:39:12.227Z",
                "id": "62021e2034b879a2b5970f57"
              },
              {
                "day": 15,
                "month": 1,
                "year": 2021,
                "sum": 1000,
                "income": true,
                "category": "addition",
                "description": "дали родители",
                "owner": {
                  "_id": "62021d2c34b879a2b5970f37",
                  "name": "TEST",
                  "email": "test@mail.com",
                  "role": "user"
                },
                "createdAt": "2022-02-08T07:40:47.831Z",
                "updatedAt": "2022-02-08T07:40:47.831Z",
                "id": "62021e7f34b879a2b5970f5d"
              }
            ]
          },
          "spending": {
            "type": "array",
            "properties": {
              "items": {
                "type": "object",
                "properties": {
                  "day": {
                    "type": "integer",
                    "description": "Day",
                    "example": "10"
                  },
                  "month": {
                    "type": "integer",
                    "description": "Month",
                    "example": "1"
                  },
                  "year": {
                    "type": "integer",
                    "description": "Year",
                    "example": "2022"
                  },
                  "sum": {
                    "type": "number",
                    "description": "Sum",
                    "example": "15000"
                  },
                  "income": {
                    "type": "boolean",
                    "example": false
                  },
                  "category": {
                    "type": "string",
                    "description": "Category",
                    "example": "salary"
                  },
                  "description": {
                    "type": "string",
                    "description": "Description",
                    "example": "зарплата"
                  },
                  "owner": {
                    "type": "object",
                    "properties": {
                      "_id": {
                        "type": "string",
                        "description": "User's id",
                        "example": "62021d2c34b879a2b5970f37"
                      },
                      "name": {
                        "type": "string",
                        "description": "User's name",
                        "example": "Rostik"
                      },
                      "email": {
                        "type": "string",
                        "description": "User's email",
                        "example": "user1@ordy.com",
                        "format": "email"
                      },
                      "role": {
                        "type": "string",
                        "description": "User's role",
                        "example": "user"
                      }
                    }
                  },
                  "createdAt": {
                    "type": "string",
                    "description": "User`s data created",
                    "example": "2022-02-04T06:27:31.669Z"
                  },
                  "updateAt": {
                    "type": "string",
                    "description": "User`s data updated",
                    "example": "2022-02-04T06:27:31.669Z"
                  },
                  "id": {
                    "type": "string",
                    "description": "User's id",
                    "example": "62025fac12117b1ff96783a2"
                  }
                }
              }
            },
            "example": [
              {
                "day": 10,
                "month": 1,
                "year": 2021,
                "sum": 15000,
                "income": false,
                "category": "salary",
                "description": "зарплата",
                "owner": {
                  "_id": "62021d2c34b879a2b5970f37",
                  "name": "TEST",
                  "email": "test@mail.com",
                  "role": "user"
                },
                "createdAt": "2022-02-08T07:39:12.227Z",
                "updatedAt": "2022-02-08T07:39:12.227Z",
                "id": "62021e2034b879a2b5970f57"
              },
              {
                "day": 15,
                "month": 1,
                "year": 2021,
                "sum": 1000,
                "income": false,
                "category": "addition",
                "description": "дали родители",
                "owner": {
                  "_id": "62021d2c34b879a2b5970f37",
                  "name": "TEST",
                  "email": "test@mail.com",
                  "role": "user"
                },
                "createdAt": "2022-02-08T07:40:47.831Z",
                "updatedAt": "2022-02-08T07:40:47.831Z",
                "id": "62021e7f34b879a2b5970f5d"
              }
            ]
          }
        }
      },
      "CreateNewTransactionRequest": {
        "type": "object",
        "properties": {
          "day": {
            "type": "integer",
            "description": "Day",
            "example": "10"
          },
          "month": {
            "type": "integer",
            "description": "Month",
            "example": "1"
          },
          "year": {
            "type": "integer",
            "description": "Year",
            "example": "2022"
          },
          "sum": {
            "type": "number",
            "description": "Sum",
            "example": "15000"
          },
          "income": {
            "type": "boolean",
            "example": true
          },
          "category": {
            "type": "string",
            "description": "Category",
            "example": "salary"
          },
          "description": {
            "type": "string",
            "description": "Description",
            "example": "зарплата"
          }
        },
        "example": {
          "day": "24",
          "month": "1",
          "year": "2022",
          "sum": "1200.62",
          "income": false,
          "category": "foods",
          "description": "супермаркет"
        }
      },
      "CreateNewTransactionResponse": {
        "type": "object",
        "properties": {
          "newTransaction": {
            "type": "object",
            "properties": {
              "result": {
                "type": "object",
                "properties": {
                  "day": {
                    "type": "integer",
                    "description": "Day",
                    "example": "10"
                  },
                  "month": {
                    "type": "integer",
                    "description": "Month",
                    "example": "1"
                  },
                  "year": {
                    "type": "integer",
                    "description": "Year",
                    "example": "2022"
                  },
                  "sum": {
                    "type": "number",
                    "description": "Sum",
                    "example": "15000"
                  },
                  "income": {
                    "type": "boolean",
                    "example": true
                  },
                  "category": {
                    "type": "string",
                    "description": "Category",
                    "example": "salary"
                  },
                  "description": {
                    "type": "string",
                    "description": "Description",
                    "example": "зарплата"
                  },
                  "owner": {
                    "type": "string",
                    "description": "Owner`s id",
                    "example": "61ff7141032d06598b989916"
                  },
                  "createdAt": {
                    "type": "string",
                    "description": "User`s data created",
                    "example": "2022-02-04T06:27:31.669Z"
                  },
                  "updateAt": {
                    "type": "string",
                    "description": "User`s data updated",
                    "example": "2022-02-04T06:27:31.669Z"
                  },
                  "id": {
                    "type": "string",
                    "description": "User's id",
                    "example": "62025fac12117b1ff96783a2"
                  }
                },
                "balance": {
                  "type": "number",
                  "description": "Current user`s balance ",
                  "example": "5000"
                }
              }
            }
          }
        },
        "example": {
          "newTransaction": {
            "result": {
              "day": 24,
              "month": 1,
              "year": 2022,
              "sum": 1200.62,
              "income": false,
              "category": "foods",
              "description": "супермаркет",
              "owner": "61ff7141032d06598b989916",
              "createdAt": "2022-02-06T11:57:39.994Z",
              "updatedAt": "2022-02-06T11:57:39.994Z",
              "id": "61ffb7b379f89b62195b9836"
            },
            "balance": 1200.62
          }
        }
      },
      "DeleteTransactionResponse": {
        "type": "object",
        "properties": {
          "deletedTransaction": {
            "type": "object",
            "properties": {
              "day": {
                "type": "integer",
                "description": "Day",
                "example": "10"
              },
              "month": {
                "type": "integer",
                "description": "Month",
                "example": "1"
              },
              "year": {
                "type": "integer",
                "description": "Year",
                "example": "2022"
              },
              "sum": {
                "type": "number",
                "description": "Sum",
                "example": "15000"
              },
              "income": {
                "type": "boolean",
                "example": true
              },
              "category": {
                "type": "string",
                "description": "Category",
                "example": "salary"
              },
              "description": {
                "type": "string",
                "description": "Description",
                "example": "зарплата"
              },
              "owner": {
                "type": "string",
                "description": "Owner`s id",
                "example": "61ff7141032d06598b989916"
              },
              "createdAt": {
                "type": "string",
                "description": "User`s data created",
                "example": "2022-02-04T06:27:31.669Z"
              },
              "updateAt": {
                "type": "string",
                "description": "User`s data updated",
                "example": "2022-02-04T06:27:31.669Z"
              },
              "id": {
                "type": "string",
                "description": "User's id",
                "example": "62025fac12117b1ff96783a2"
              }
            }
          }
        },
        "example": {
          "deletedTransaction": {
            "day": 15,
            "month": 1,
            "year": 2021,
            "sum": 1000,
            "income": true,
            "category": "addition",
            "description": "дали родители",
            "owner": "62021d2c34b879a2b5970f37",
            "createdAt": "2022-02-08T07:40:47.831Z",
            "updatedAt": "2022-02-08T07:40:47.831Z",
            "id": "62021e7f34b879a2b5970f5d"
          }
        }
      },

      "securitySchemes": {
        "Bearer": {
          "type": "http",
          "scheme": "bearer",
          "bearerFormat": "JWT"
        }
      }
    }
  }
}
